Задание 2. Разметка главной страницы
htmlacademy-htmlcss/587963-gllacy-30 pull request #1
Opened 2021-01-23 16:07 UTC by ShmApple

2021-01-23 21:13 UTC, Zakamsky requested changes
Верстка почти эталонная, но видимо чуть чуть расслабился и есть небольшие оплошности. Чувствуется что старался, но кажется немного невнимательно, т.к. потерян один заголовок и ошибочка с уровнем у второго.
еще нехватает элементов в карточке товара. В отсальном отлично.

2021-01-23 21:13 UTC, Zakamsky commented on index.html
> +      <img src="https://via.placeholder.com/154x64" width="154" height="64" alt="GllacyShop">
на других страницах это ссылка на главную, Возможно стоит сохранить единообразную структуру, но это конечно не ошибка. в чате еще об этом напишу.

2021-01-23 21:13 UTC, Zakamsky commented on index.html
> +        <ul class="carousel__list">
Секции очень хочет иметь заголовок, хотя бы скрытый.

2021-01-23 21:13 UTC, Zakamsky commented on index.html
> +        <ul class="carousel__list">
Кстати, в макете есть еще три кнопочки для каждого слайда, они кажется потерялись.

2021-01-23 21:13 UTC, Zakamsky commented on index.html
> +          </li>
А вот тут у нас карточки товаров...
во первых, где то тут должна быть ссылка на страницу товара, во вторых, в тз сказано что поведение элемента совпадает со страницей каталога и указано в стайлгайде, где видны дополнительные элементы.

2021-01-23 21:13 UTC, Zakamsky commented on index.html
> +          <h1>Новое в нашем блоге</h1>
воу, ну это наверное опечатка...

2021-01-24 07:49 UTC, ShmApple commented on index.html
> +          </li>
Точно, свершенно забыл про это.

2021-01-24 07:50 UTC, ShmApple commented on index.html
> +          <h1>Новое в нашем блоге</h1>
Забылся, и перепутал использование заголовков внутри тегов article и section :)

2021-01-24 08:06 UTC, ShmApple commented on index.html
> +        <ul class="carousel__list">
По поводу заголовка вчера полвечера ломал голову :) Так и не смог придумать, как назвать эту секцию. Думаю, что-то вроде «Новинки и хиты», но не уверен. Зависит от того, что именно означают эти баннеры.

Про кнопочки помнил, думал, что пока их размечать не нужно, потому как в дальнейшем нужно будет переделывать их под input'ы, чтобы смена работала без JS. Но уже разметил их пока ссылками, т.к. не помню уже, как это реализовать без JS, да и рановато :)

2021-01-24 13:06 UTC, Zakamsky commented on index.html
> +        <ul class="carousel__list">
не надо пожалуйста реализаций без JS.. То ка4к сейчас сделано - примелимо и хорошо. хотя к ссылкам могут и придраться (з.ы. учу плохому можно по ссылке ловить фокус на элементе и его показывать т.е. тоже без JS. =) у меня так один студент показывал и скрывал попапы... пока его за руку не поймали)

2021-01-24 13:09 UTC, merged